## Importing Numpy and how to make List/Array with Numpy


In [1]:
import numpy as np

list_data = [1, 2, 3]
arr = np.array(list_data)

print(arr.size)
print(arr.dtype)
print(arr[2])

3
int64
3


## Some basic operations in Numpy

In [5]:
# creating 1d array [0, 1, 2, 3] (from 0 to 3)
# you can think of this like for i in range(4)
arr1 = np.arange(4)
print("arr1:\n", arr1)

# create a 4x4 2d array(matrix) with value float 0
arr2 = np.zeros((4, 4), dtype = float)
print("arr2:\n", arr2)

# create a 3x3 2d array(matrix) with value string 1
arr3 = np.ones((3, 3), dtype=str)
print("arr3:\n", arr3)

# create a 3x3 2d array(matrix) with random values 0 to 9
arr4 = np.random.randint(0, 10, (3, 3))
print("arr4:\n", arr4)

# create a 3x3 2d array(matrix) where mean value is 0 with standard deviation of 1
arr5 = np.random.normal(0, 1, (3, 3))
print("arr5:\n", arr5)

arr1:
 [0 1 2 3]
arr2:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
arr3:
 [['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
arr4:
 [[9 2 6]
 [7 9 0]
 [6 5 4]]
arr5:
 [[ 0.66755247 -0.16216641  0.81601341]
 [ 0.7853595  -0.58722737  0.2097311 ]
 [ 1.24401384  0.39303442 -1.37390758]]


## Merging two array using Numpy

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# merge two array arr1, arr2 in a 1D array(vector)
arr3 = np.concatenate([arr1, arr2])

print(arr3.shape)
print(arr3)

(6,)
[1 2 3 4 5 6]


## Using Reshape allows array to be in different shape

In [14]:
# array 1 is a 1x4 array
arr1 = np.array([1,2,3,4])
# using reshape to make 2x2 array
arr2 = arr1.reshape((2,2))
print("arr2 shape\n", arr2.shape)
print("arr2\n", arr2)

arr2 shape
 (2, 2)
arr2
 [[1 2]
 [3 4]]


## More example on Concatenate and Reshape

In [21]:
# create a 1x4 matrix from 0 to 3
arr1 = np.arange(4).reshape(1, 4)
# create 2x4 matrix from 0 to 7
arr2 = np.arange(8).reshape(2, 4)

print("arr1\n", arr1)
print("arr2\n", arr2)

# merge two array
arr3 = np.concatenate([arr1, arr2], axis=0)
print("arr3\n", arr3)

arr1
 [[0 1 2 3]]
arr2
 [[0 1 2 3]
 [4 5 6 7]]
arr3
 [[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


## We can also split the array

In [20]:
# create a 2x4 matrix from 0 to 7
arr = np.arange(8).reshape(2, 4)
print("arr\n", arr)

#split the array into 2 vertically
left, right = np.split(arr, [2], axis=1)

print("left\n", left)
print("right\n", right)



arr
 [[0 1 2 3]
 [4 5 6 7]]
left
 [[0 1]
 [4 5]]
right
 [[2 3]
 [6 7]]
