<a href="https://colab.research.google.com/github/hyeonukim/DataProcessing_ImageHandling/blob/main/How_to_handle_Data%2C_and_Images(3)_Numpy's_Usage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python's Numpy is capable of saving and loading data

In [1]:
import numpy as np

# create an array with 0-9
arr = np.arange(0,10)
# save the corresponding array to saved.npy
np.save('saved.npy', arr)

# load the corresponding data to res
res = np.load('saved.npy')
print(res)

[0 1 2 3 4 5 6 7 8 9]


## Saving multiple arrays

In [2]:
arr1 = np.arange(0, 10)
arr2 = np.arange(10, 20)
np.savez('saved.npz', arr1=arr1, arr2=arr2)

data = np.load('saved.npz')
res1 = data['arr1']
res2 = data['arr2']
print("res1\n", res1)
print("res2\n", res2)

res1
 [0 1 2 3 4 5 6 7 8 9]
res2
 [10 11 12 13 14 15 16 17 18 19]


## Sorting in Numpy

In [6]:
# sorting smallest to biggest
arr = np.array([5, 9, 10, 3, 1])
arr.sort()
print("arr\n", arr)

# sorting biggest to smallest
arr = np.array([5, 9, 10, 3, 1])
arr.sort()
print("arr\n", arr[::-1])

# sorting 2d array by column
arr = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
arr.sort(axis=0)
print("arr\n", arr)

# sorting 2d array by row
arr = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
arr.sort(axis=1)
print("arr\n", arr)

arr
 [ 1  3  5  9 10]
arr
 [10  9  5  3  1]
arr
 [[ 5  3  4  2  1]
 [ 8  9 10  3  5]]
arr
 [[ 1  3  5  9 10]
 [ 2  3  4  5  8]]


## More functions that are commonly used in Numpy

In [10]:
# create an array for 5 elements from 0 to 10 evenly spaced
arr = np.linspace(0, 10, 5)
print("arr\n", arr)

# random with seed allows us to reenact
np.random.seed(7)
print("random seed (7)\n", np.random.randint(0, 10, (2,3)))

# copying array
arr1 = np.arange(0, 10)
arr2 = arr1.copy()
print("arr2\n", arr2)

# removes repeated elements
arr = np.array([1, 1, 2, 3, 3, 3, 1])
print("np.unique\n", np.unique(arr))

arr
 [ 0.   2.5  5.   7.5 10. ]
random seed (7)
 [[4 9 6]
 [3 3 7]]
arr2
 [0 1 2 3 4 5 6 7 8 9]
np.unique
 [1 2 3]
